lidar:
  extrinsic_T: [ -0.016, 0, 0 ]
  extrinsic_R: [ 0.7071, 0, -0.7071,
                0, 1, 0,
                0.7071, 0, 0.7071]
  # extrinsic_T: [ -0.018, 0, 0 ]
  # extrinsic_R: [ 1, 0, 0,
  #                0, 1, 0,
  #                0, 0, 1]
  # extrinsic_T: [0, 0, -0.32]
  # extrinsic_R: [1, 0, 0,
  #               0, -1, 0,
  #               0, 0, -1]