name: Build-CI

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-20.04
    container:
      image: ghcr.io/irobot-algorithm/sentry_navigation:latest  # 替换为你的基础镜像
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Start SSH Service
      uses: mxschmitt/action-tmate@v2

    - name: Run the CI process inside Docker container
      run: |
        echo '### 构建工作区 ###'
        sudo chmod 777 build.sh
        ./build.sh

        echo '### 运行测试 ###'
        source /opt/ros/noetic/setup.sh
        catkin_test_results build